### ISSUE TITLE
[spring boot] ./gradlew diffChangeLog isn't updating changelog correctly

### ISSUE THREAD

**Issue by nelson687se** [liquibase/liquibase-gradle-plugin#47] opened 2018-10-05 16:41 UTC
When I run `./gradlew diffChangeLog`, liquibase detects the changes but when it modifies my `changelog.groovy` it inserts the new lines with formatting errors or typos. Like a wrong merge conflict fix.
For example, after running that command, this is being inserted in `changelog.groovy`
```
lumn(name: 'testTable', type: 'INT')
      column(name: 'name', type: 'VARCHAR(255)')
      column(name: 'priority', type: 'INT')
      column(name: 'timezone', type: 'VARCHAR(255)')
      column(name: 'type', type: 'VARCHAR(255)')
    }
  }
```

instead of `Column` it says `lumn` - Also, the whole `databaseChangeLog` block closes and then, after the closing curly brace, there are more changesets inserted. Which shouldn't be happening.
Tried with the` groovy liquibase dsl` plugin and also with the yaml version and in both cases the same is happening.

**Comment by stevesaliman** [comment] 2018-10-06 20:13
I'm not sure what might be going on.  I just tried running `gradlew diffChangeLog` on one of my projects and it generated a changelog that was over 5,000 lines long without any syntax problems on a Linux system.  

My project is not (yet) a Spring Boot project, but I don't think that would be an issue with Gradle.  Is there any chance that another process was trying to access the changelog file at the same time?

**Comment by nelson687se** [comment] 2018-10-08 13:13
`buildscript {
	ext {
		springBootVersion = '2.0.5.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
		classpath 'org.liquibase.ext:liquibase-hibernate5:3.6'
	}
}

plugins {
    id 'java'
    id 'eclipse'
    id 'org.springframework.boot' version '2.0.5.RELEASE'
    id 'io.spring.dependency-management' version '1.0.6.RELEASE'
	id 'org.liquibase.gradle' version '2.0.1'
}

group = 'com.flashsales.flights'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
	mavenCentral()
}

dependencies {
	compileOnly('org.projectlombok:lombok:1.16.20')
	compile('org.springframework.boot:spring-boot-starter-web')
	compile ("org.springframework.boot:spring-boot-starter-data-jpa")
	compile ('mysql:mysql-connector-java')
	compile('org.liquibase:liquibase-core')
	compile('org.liquibase:liquibase-groovy-dsl:2.0.1')
	runtime('org.springframework.boot:spring-boot-devtools')
	testImplementation('org.springframework.boot:spring-boot-starter-test')
	testCompile(group:'net.bytebuddy', name:'byte-buddy', version:'1.8.22')
	liquibaseRuntime 'org.liquibase:liquibase-core'
	liquibaseRuntime 'org.liquibase:liquibase-groovy-dsl:2.0.1'
	liquibaseRuntime 'mysql:mysql-connector-java'
	liquibaseRuntime 'org.springframework.boot:spring-boot-starter-data-jpa'
	liquibaseRuntime 'org.springframework.boot:spring-boot-starter-web'
	liquibaseRuntime 'org.liquibase.ext:liquibase-hibernate5:3.6'
	liquibaseRuntime sourceSets.main.output
}

liquibase {
  activities {
    main {
      changeLogFile 'src/main/resources/db/changelog/changelog.groovy'
      url 'jdbc:mysql://localhost:3306/fsb?autoReconnect=true'
	  referenceUrl 'hibernate:spring:com.secretescapes.flights.domain?dialect=org.hibernate.dialect.MySQLDialect'
      username 'root'
      password ''
    }
  }
}
`

That's my build.gradle file.
What I do is:
I first run: `./gradlew generateChangelog` - Then `./gradlew diffChangeLog` and everything is fine. I run the app, and it creates the database changes. After that, I make a change in a domain class (deleting or adding a property), and want to generate the changeset for that change so I run again `./gradlew diffChangeLog` and this is when the `changelog.groovy` gets messed up.

**Comment by stevesaliman** [comment] 2018-10-11 01:45
My guess is that the hibernate plugin might be interfering somehow.  Do you have a sample project that shows the problem that I could use to debug how the plugin reacts?

**Comment by nelson687se** [comment] 2018-10-16 13:53
Sure, I've uploaded this: https://github.com/nelson687/springboot-liquibase - At the moment, after doing a `./gradlew clean`, and dropping the database and creating a new clean one, I created a new changelog file with `./gradlew generateChangelog` and then when I run `./gradlew diffChangeLog` it doesn't do anything, and it leaves the changelog.groovy empty.

**Comment by stevesaliman** [comment] 2018-10-21 18:11
A can now reproduce the problem, but I'm not sure what could be causing it.  I'm pretty sure the error is in the Liquiabse Groovy DSL.  I'll keep working on it.

**Comment by nelson687se** [comment] 2018-10-22 09:11
I tried without the Liquibase Groovy DSL and it's also happening the same.

**Comment by stevesaliman** [comment] 2018-10-22 14:53
I seem to remember trying it without the DSL and having it do the right thing.  I'll have to try it again to be sure.

I would be a bit surprised if the issue did wind up being a plugin issue since the plugin is just a thin wrapper around the main Liquibase method.

At the moment, the only workaround I can think of is to re-run generateChangeLog to recreate the changelog from scratch.  However, if it changes the ids of the changesets, that won't help much.

I will work on a fix for this issue as soon as I can.  Next weekend is out for me, but I should be able to work on it the following weekend.

**Comment by stevesaliman** [comment] 2023-03-05 16:36
Closing due to inactivity.  This can't be fixed without resolving the underlying Liquibase issue, and there hasn't been any movement on that issue in 5 years.

**Closed by stevesaliman** 2023-03-05 16:36 UTC
