### ISSUE TITLE
Could not find or load main class 1.1 out of SpringToolSuite/Eclipse

### ISSUE THREAD

**Issue by GrizzlyBoer** [liquibase/liquibase-gradle-plugin#67] opened 2020-03-31 07:57 UTC
Hi,

I just started with your liquibase-plugin and love it.
My plan ist to use it with my Spring-Boot apps.

However I'm stuck here with one issue with Windows10 as OS.
If i run a Liquibase-Task from my command line with for example "gradlew generateChangeLog" everything works just fine.

The same command with SpringToolSuite (STS) with double click generateChangeLog under "Gradle Tasks" and I get:
```error
Working Directory: D:\STS_POC_Worcspace\poc_liquibase
Gradle user home: C:\Users\Grizzly\.gradle
Gradle Distribution: Gradle wrapper from target build
Gradle Version: 6.2.2
Java Home: D:\Java\Java13\jdk-13.0.2
JVM Arguments: None
Program Arguments: None
Build Scans Enabled: false
Offline Mode Enabled: false
Gradle Tasks: generateChangelog

> Task :compileJava UP-TO-DATE

> Task :generateChangelog FAILED
liquibase-plugin: Running the 'main' activity...
Error: Could not find or load main class 1.1,
Caused by: java.lang.ClassNotFoundException: 1.1,

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateChangelog'.
> Process 'command 'D:\Java\Java13\jdk-13.0.2\bin\java.exe'' finished with non-zero exit value 1

BUILD FAILED in 1s
2 actionable tasks: 1 executed, 1 up-to-date
```

This is not a very big issue as I prefer the command-line anyways.
But i would like to know if you ever used STS or Eclipse with Buildship and ran into similar problems.

Also I should be able to explain it to my colleagues if i tell them not to Use the GUI for liquibase-tasks

Btw. the difference is only with the liquibase-tasks. All other Tasks are executing from cmd and STS/Eclipse

This is my build-file
```gradle
plugins{

	id 'org.springframework.boot' version '2.2.6.RELEASE'
	id 'org.liquibase.gradle' version '2.0.2'
}

apply plugin: 'io.spring.dependency-management'
apply plugin: 'java'

group = 'de.dsv.spring'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '13'

repositories {
        mavenCentral()
}

configurations {
	customRuntime
	runtimeOnly.extendsFrom customRuntime
	liquibaseRuntime.extendsFrom customRuntime
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-logging'

	customRuntime 'com.ibm.db2:jcc'

	liquibaseRuntime 'org.liquibase:liquibase-core:3.8.+'
	liquibaseRuntime "org.liquibase:liquibase-gradle-plugin:2.0.1"
	liquibaseRuntime 'org.liquibase.ext:liquibase-hibernate5:3.8' 
	liquibaseRuntime 'ch.qos.logback:logback-core:1.2.3'
        liquibaseRuntime 'ch.qos.logback:logback-classic:1.2.3'
	liquibaseRuntime sourceSets.main.output
	
	testImplementation('org.springframework.boot:spring-boot-starter-test') {
		exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
	}
}

liquibase {
	activities {
    	main {
    	  changeSetAuthor "gradle"
    	  changeLogFile "${this.rootDir}/src/main/resources/DB/changelog-V4.xml"
	      url 'jdbc:db2://url;'
	      username 'user'
	      password 'password'
	      referenceUrl 'hibernate:spring:de.dsv.poc.example.accessingdatajpa?dialect=org.hibernate.dialect.DB2Dialect&hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy'
	    }
    }
    runList = 'main'
}

diff.dependsOn compileJava
diffChangeLog.dependsOn compileJava
generateChangelog.dependsOn compileJava

test {
	useJUnitPlatform()
}
```

**Comment by lucasmontec** [comment] 2020-04-22 20:53
I'm having the exact same issue on Eclipse. It runs fine using the wrapper via CLI. Use that as a workaround.

**Comment by stevesaliman** [comment] 2021-01-24 17:47
I'm an Intellij user, so I have no idea what Eclipse might be doing.  In theory, it should just invoke Gradle the same as the Command line would, but since the CLI seems to work fine, I'm closing this.  If anyone can suggest something the plugin is doing that confuses Eclipse (and STS), I can reopen this issue.

**Closed by stevesaliman** 2021-01-24 17:47 UTC

**Comment by keigo-brook** [comment] 2021-03-27 09:49
Hi, This error also happens when I'm using Windows 10 and Eclipse (STS).
The error relates  this issue: https://github.com/gradle/gradle/issues/6072

Windows has an error when it pass the system property with quotes and spaces to Java.
Eclipse sets several system properties and one of these contains spaces.
For example, my environment, STS 4.9.0.RELEASE, set a system property `org.osgi.framework.system.capabilities`
and its value is:
```
"osgi.ee; osgi.ee="OSGi/Minimum"; version:List<Version>="1.0, 1.1, 1.2", osgi.ee; osgi.ee="JRE"; version:List<Version>="1.0, 1.1", osgi.ee; osgi.ee="JavaSE"; version:List<Version>="1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 9.0, 10.0, 11.0",osgi.ee; osgi.ee="JavaSE/compact1"; version:List<Version>="1.8, 9.0, 10.0, 11.0",osgi.ee; osgi.ee="JavaSE/compact2"; version:List<Version>="1.8, 9.0, 10.0, 11.0",osgi.ee; osgi.ee="JavaSE/compact3"; version:List<Version>="1.8, 9.0, 10.0, 11.0""
```
So it seems the error message `could not find or load main class 1.1` is caused by `version:List<Version>="1.0, 1.1, 1.2",`.

To avoid this error, set `System.getProperties().remove('org.osgi.framework.system.capabilities')` to `build.gradle`.
I searched a little to remove the property from eclipse or its running configuration, but I can't find.
